// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { LocaleProvider } from "@/contexts/locale-context";
import { TokensProvider } from "@/contexts/tokens-context";
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";
import AgeGate from "@/components/custom/age-gate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meu Sugar - Conversas Premium com IA",
  description: "Plataforma premium de conversas com IA personalizadas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <AgeGate />
        <LocaleProvider>
          <TokensProvider>
            <Header />
            <main className="pt-20">
              {children}
            </main>
            <Footer />
          </TokensProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
